name: 'Wait'
env: 
  PASSWORD: ${{ secrets.PASSWORD }}
  EMAIL: ${{ secrets.EMAIL }}
description: 'one-way sync your overleaf projects to github (two-way coming soon)'
inputs:
  project:  # id of input
    description: 'project id to sync only one'
    required: false
    default: '1000'
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
