name: 'overleaf-sync'
description: 'one-way sync your overleaf projects to github (two-way coming soon(tm))'
icon: check-circle
color: green
inputs:
  password:
    description: 'your password for your overleaf account'
    required: true
  email:
    description: 'your email for your overleaf account'
    required: true
  repotoken:
    description: 'The GITHUB_TOKEN secret'
    required: true
  gitemail:
    description: 'Your github account email'
    required: true
  gituser:
    description: 'Your github username'
    required: true
  reponame:
    description: 'Your github repo name (where to sync your projects)'
    required: true
outputs:
  time:
    description: 'The time it took to sync'
runs:
  using: 'node12'
  main: 'dist/index.js'
